volumes:
  geth:
  node:

services:
  geth:
    image: ${GETH_IMAGE}
    ports:
      # geth http rpc
      - "8545:8545"
      # geth ws rpc
      - "8546:8546"
      # geth eignine authrpc
      - "8551:8551"
      # geth metrics
      - "6060:6060"
      # geth p2p port
      - "30303:30303"
    volumes:
      - "geth:/data"
      - "./jwt.txt:/jwt.txt"
    environment:
      - SEQUENCER_HTTP=${SEQUENCER_HTTP}
      - BOOTNODES=${BOOTNODES}
      - GENESIS_URL=${GENESIS_URL}
      - SYNC_MODE=${SYNC_MODE:-full}
      - GC_MODE=${SYNC_MODE:-archive}
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        # do geth init if datadir is empty
        if [ ! -d "/data/geth" ]; then
            echo "Initializing geth datadir"
            wget -O /data/genesis.json $GENESIS_URL
            geth init --datadir=/data /data/genesis.json
        else
            echo "geth datadir already initialized, skipping..."
        fi
        geth \
            --datadir=/data \
            --rollup.disabletxpoolgossip=true \
            --rollup.sequencerhttp=$SEQUENCER_HTTP \
            --http \
            --http.corsdomain="*" \
            --http.vhosts="*" \
            --http.addr=0.0.0.0 \
            --http.api=web3,debug,eth,txpool,net,engine \
            --ws \
            --ws.addr=0.0.0.0 \
            --ws.api=web3,debug,eth,txpool,net,engine \
            --authrpc.addr=0.0.0.0 \
            --authrpc.vhosts="*" \
            --authrpc.port=8551 \
            --authrpc.jwtsecret=/jwt.txt \
            --bootnodes=$BOOTNODES \
            --metrics \
            --syncmode=$SYNC_MODE \
            --gcmode=$GC_MODE

  node:
    depends_on:
      - geth
    image: ${NODE_IMAGE}
    ports:
      # node rpc
      - "9545:9545"
      # node p2p 
      - "9003:9003"
      # node metrics
      - "7300:7300"
    volumes:
      - "node:/data"
      - "./jwt.txt:/jwt.txt"
    env_file:
      - opnode.env
    environment:
      - ROLLUP_CONFIG_URL=${ROLLUP_CONFIG_URL}
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        until nc -z -w 5 geth 8551; do
            echo "Waiting for geth ..."
            sleep 5
        done
        echo "geth is up"

        if [ ! -f "/data/rollup.json" ]; then
            wget -O /data/rollup.json $ROLLUP_CONFIG_URL
        fi

        mkdir -p /data/opnode_discovery_db
        mkdir -p /data/opnode_peerstore_db
        mkdir -p /data/safedb

        op-node \
            --syncmode=execution-layer \
            --rollup.config=/data/rollup.json \
            --safedb.path=/data/safedb \
            --l1.trustrpc \
            --l1.beacon.ignore \
            --l2=http://geth:8551 \
            --l2.jwt-secret=/jwt.txt \
            --metrics.enabled \
            --p2p.listen.ip=0.0.0.0 \
            --p2p.listen.tcp=9003 \
            --p2p.listen.udp=9003 \
            --p2p.discovery.path=/data/opnode_discovery_db \
            --p2p.peerstore.path=/data/opnode_peerstore_db \
            --p2p.priv.path=/data/opnode_p2p_priv.txt 
